---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k8s.shanbay.io.shanbay.com
  resources:
  - canarydeployplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.shanbay.io.shanbay.com
  resources:
  - canarydeployplans/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.shanbay.io.shanbay.com
  resources:
  - canarydeployplans/status
  verbs:
  - get
  - patch
  - update
